# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-01 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeGuess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP address')),
                ('when_tried', models.DateTimeField(auto_now=True, verbose_name='When')),
                ('guess_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Invitation code guessed')),
            ],
            options={
                'verbose_name': 'Invitation code guess',
                'verbose_name_plural': 'Invitation code guesses',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('schedule', models.TextField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('date', models.DateTimeField(verbose_name='event date')),
                ('public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=45, null=True)),
                ('last_name', models.CharField(blank=True, max_length=45, null=True)),
                ('first_name_2', models.CharField(blank=True, max_length=45, null=True)),
                ('last_name_2', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('street_address_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('side', models.BooleanField(choices=[(True, 'Groom'), (False, 'Bride')])),
                ('relation', models.PositiveSmallIntegerField(choices=[(0, 'Immediate Family'), (1, 'Paternal Family'), (2, 'Maternal Family'), (3, 'Friend')])),
                ('invite_code', models.CharField(help_text='leave it empty, it will be generated automatically on creation of invitation', max_length=4, unique=True, verbose_name='invitation code')),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attending', models.NullBooleanField()),
                ('adults', models.IntegerField(blank=True, null=True)),
                ('children', models.IntegerField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite', to='weddings.Event')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite', to='weddings.Guest')),
            ],
        ),
        migrations.CreateModel(
            name='Lodging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('events', models.ManyToManyField(to='weddings.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.CharField(max_length=255)),
                ('events', models.ManyToManyField(to='weddings.Event')),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='events',
            field=models.ManyToManyField(through='weddings.Invite', to='weddings.Event'),
        ),
    ]
