# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='event date')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=45, null=True)),
                ('last_name', models.CharField(blank=True, max_length=45, null=True)),
                ('first_name_2', models.CharField(blank=True, max_length=45, null=True)),
                ('last_name_2', models.CharField(blank=True, max_length=45, null=True)),
                ('attending', models.BooleanField()),
                ('primary_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('street_addr', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zip_code', models.IntegerField(blank=True, max_length=5, null=True)),
                ('primary', models.NullBooleanField()),
                ('groom', models.BooleanField(default=False)),
                ('relation', models.PositiveSmallIntegerField(choices=[(0, 'Immediate'), (1, 'Paternal'), (2, 'Maternal'), (3, 'Friend')])),
                ('events', models.ManyToManyField(blank=True, null=True, to='weddings.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.CharField(help_text='leave it empty, it will be generated automatically on creation of invitation', max_length=6, verbose_name='invitation code')),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weddings.Invitation', verbose_name='Invitation letter guest is assigned'),
        ),
    ]
