# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-01 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='events',
            new_name='invites',
        ),
    ]
