# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
