# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lodging',
            name='events',
        ),
        migrations.RemoveField(
            model_name='registry',
            name='events',
        ),
    ]
