# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-07 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0002_auto_20160605_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lodging',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='lodging',
            name='longitude',
        ),
        migrations.AddField(
            model_name='lodging',
            name='map_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registry',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
