# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-07 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0003_auto_20160607_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='event',
            name='longitude',
        ),
        migrations.AddField(
            model_name='event',
            name='map_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
