# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0003_remove_guest_primary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='events',
        ),
        migrations.AddField(
            model_name='guest',
            name='event',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='weddings.Event'),
        ),
    ]
