# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-02 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0004_auto_20160601_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attending', models.NullBooleanField()),
                ('adults', models.IntegerField(blank=True, null=True)),
                ('children', models.IntegerField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='weddings.Event')),
            ],
        ),
        migrations.RemoveField(
            model_name='invite',
            name='event',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='invites',
        ),
        migrations.DeleteModel(
            name='Invite',
        ),
        migrations.AddField(
            model_name='guestevent',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='weddings.Guest'),
        ),
        migrations.AddField(
            model_name='event',
            name='guests',
            field=models.ManyToManyField(through='weddings.GuestEvent', to='weddings.Guest'),
        ),
        migrations.AddField(
            model_name='guest',
            name='events',
            field=models.ManyToManyField(through='weddings.GuestEvent', to='weddings.Event'),
        ),
    ]
