# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-07 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0004_auto_20160607_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='map_url',
            new_name='map_embed',
        ),
        migrations.RenameField(
            model_name='lodging',
            old_name='map_url',
            new_name='map_embed',
        ),
    ]
