# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0004_auto_20160325_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='groom',
        ),
        migrations.AddField(
            model_name='guest',
            name='side',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Groom'), (1, 'Bride')], default=0),
            preserve_default=False,
        ),
    ]
