# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-07 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0005_auto_20160607_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='map_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lodging',
            name='map_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
