# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-08 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0006_auto_20160607_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='guestevent',
            name='attending',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
