# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-08 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0007_auto_20160608_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='image',
            field=models.ImageField(null=True, upload_to='media/registry/'),
        ),
    ]
