# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0007_auto_20160405_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='attending',
        ),
    ]
