# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0008_remove_guest_attending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='location_address',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location_url',
        ),
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
