# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0010_auto_20160411_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='invitation',
        ),
        migrations.AddField(
            model_name='guest',
            name='invite_code',
            field=models.CharField(default=123456, help_text='leave it empty, it will be generated automatically on creation of invitation', max_length=6, verbose_name='invitation code'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
