# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0011_auto_20160412_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='street_addr',
            new_name='street_address',
        ),
        migrations.AddField(
            model_name='guest',
            name='street_address_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
