# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0012_auto_20160412_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeGuess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP address')),
                ('when_tried', models.DateTimeField(auto_now=True, verbose_name='When')),
                ('guess_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Invitation code guessed')),
            ],
            options={
                'verbose_name_plural': 'Invitation code guesses',
                'verbose_name': 'Invitation code guess',
            },
        ),
        migrations.AlterField(
            model_name='guest',
            name='invite_code',
            field=models.CharField(help_text='leave it empty, it will be generated automatically on creation of invitation', max_length=6, unique=True, verbose_name='invitation code'),
        ),
    ]
