# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0013_auto_20160413_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='primary_email',
            new_name='email',
        ),
    ]
