# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0015_lodging_registry'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='adults',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='children',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='relation',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Immediate Family'), (1, 'Paternal Family'), (2, 'Maternal Family'), (3, 'Friend')]),
        ),
    ]
