# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0016_auto_20160503_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='attending',
            field=models.NullBooleanField(),
        ),
    ]
