# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-25 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0017_guest_attending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='event',
        ),
        migrations.AddField(
            model_name='guest',
            name='events',
            field=models.ManyToManyField(to='weddings.Event'),
        ),
    ]
